{
  "formatVersion": "1.1",
  "component": {
    "url": "../../library/1.0.2-local/library-1.0.2-local.module",
    "group": "com.lagradost.api",
    "module": "library",
    "version": "1.0.2-local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "library.aar",
          "url": "library-android-1.0.2-local.aar",
          "size": 1904941,
          "sha512": "217fb8b6e7a0f4733dd048d447090da26ce1d03d87e1e2cec248fe9117e3b4a68337fa2ab3528ee4371c2b15131f93fc7630c05bb34ac1086769a130456a05e4",
          "sha256": "b767ab1b32f40901db70f48ed2a7bdfa3003e01af372216b72a40ebd7505c672",
          "sha1": "1411e8904b78a35b0eee13b4b5f9f9d982c0bdcf",
          "md5": "2952a63d9467ec77e7e1c10bdd34e2b6"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "strictly": "2.13.1",
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.22.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.Blatzar",
          "module": "NiceHttp",
          "version": {
            "requires": "0.4.18"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "strictly": "1.8.1",
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.uwetrottmann.tmdb2",
          "module": "tmdb-java",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-optimal",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.github.teamnewpipe",
          "module": "NewPipeExtractor",
          "version": {
            "requires": "v0.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "library.aar",
          "url": "library-android-1.0.2-local.aar",
          "size": 1904941,
          "sha512": "217fb8b6e7a0f4733dd048d447090da26ce1d03d87e1e2cec248fe9117e3b4a68337fa2ab3528ee4371c2b15131f93fc7630c05bb34ac1086769a130456a05e4",
          "sha256": "b767ab1b32f40901db70f48ed2a7bdfa3003e01af372216b72a40ebd7505c672",
          "sha1": "1411e8904b78a35b0eee13b4b5f9f9d982c0bdcf",
          "md5": "2952a63d9467ec77e7e1c10bdd34e2b6"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "library-android-1.0.2-local-sources.jar",
          "url": "library-android-1.0.2-local-sources.jar",
          "size": 224617,
          "sha512": "ccd6cf821d24c2200bf21eee08f9409a2c77d4470a8749c10e00995940c81ee4f3547fff4e3d810fea2f717ea9ad93335e24aa7a9fcaf957d6a812708120bc89",
          "sha256": "4685fd723bbb151130252643c75b1d1e2270f1fe23a0f863d177257b4c926154",
          "sha1": "a54489433e9ff4532b99a1a14d7d2bdf9a6800f3",
          "md5": "624ee5eb97054760a2a7fa01572cf2e8"
        }
      ]
    }
  ]
}
